name: Build

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  binary: client
  game_name: arena-shooter

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      # TODO: eventuall we should use this cache action in all jobs
      - uses: Swatinem/rust-cache@v2
      - name: Cargo format
        run: |
          cargo fmt --all -- --check
      - name: Install system dependencies
        run: |
          sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev mold clang
      - name: Cargo check
        # we create empty assets directory so build of `bevy_embedded_assets` wont fail
        run: |
          mkdir assets
          cargo clippy -- -D unused-imports -D unused-variables -D clippy::needless_update

  # Build for Linux
  build-linux:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install system dependencies
        run: |
          sudo apt-get update; sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev mold zip

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download assets from google drive
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}    
          GDRIVE_ASSETS_DIRECTORY_ID: ${{ secrets.GDRIVE_ASSETS_DIRECTORY_ID }}
        run: |
          sudo apt install -y rclone

          echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > /tmp/sa.json

          export RCLONE_CONFIG_GDRIVE_TYPE=drive
          export RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE=/tmp/sa.json
          export RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID=$GDRIVE_ASSETS_DIRECTORY_ID

          rclone copy gdrive:assets assets/

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu -p client --no-default-features

      - name: Prepare package
        run: |
          mv target/x86_64-unknown-linux-gnu/release/${{ env.binary }} ${{ env.game_name }}

      - name: Package as a zip
        run: |
          zip ${{ env.game_name}}-linux.zip ${{ env.game_name }}

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.game_name }}-linux.zip
          archive: false

  # Build for Windows
  build-windows:
    needs: check
    runs-on: windows-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download assets from google drive
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_ASSETS_DIRECTORY_ID: ${{ secrets.GDRIVE_ASSETS_DIRECTORY_ID }}
        run: |
          winget install rclone --accept-package-agreements --accept-source-agreements

          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          refreshenv

          $env:GDRIVE_SERVICE_ACCOUNT_JSON | Out-File -Encoding utf8 $env:TEMP\sa.json

          $env:RCLONE_CONFIG_GDRIVE_TYPE = "drive"
          $env:RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE = "$env:TEMP\sa.json"
          $env:RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID = $env:GDRIVE_ASSETS_DIRECTORY_ID

          rclone copy gdrive:assets assets/

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc -p client --no-default-features

      - name: Prepare package
        run: |
          mv target/x86_64-pc-windows-msvc/release/${{ env.binary }}.exe ${{ env.game_name }}.exe

      - name: Package as a zip
        run: |
          Compress-Archive -Path ${{ env.game_name }}.exe -DestinationPath ${{ env.game_name }}-windows.zip

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.game_name }}-windows.zip
          archive: false

  # Build for MacOS x86_64
  build-macOS-intel:
    needs: check
    runs-on: macOS-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
      - name: Environment Setup
        run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download assets from google drive
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}    
          GDRIVE_ASSETS_DIRECTORY_ID: ${{ secrets.GDRIVE_ASSETS_DIRECTORY_ID }}
        run: |
          brew install rclone

          echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > /tmp/sa.json

          export RCLONE_CONFIG_GDRIVE_TYPE=drive
          export RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE=/tmp/sa.json
          export RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID=$GDRIVE_ASSETS_DIRECTORY_ID

          rclone copy gdrive:assets assets/

      - name: Build
        run: |
          rustup target add x86_64-apple-darwin
          cargo build --release --target x86_64-apple-darwin -p client --no-default-features

      - name: Prepare Package
        run: |
          mkdir -p arena-shooter.app/Contents/MacOS
          cp target/x86_64-apple-darwin/release/${{ env.binary }} ${{ env.game_name }}.app/Contents/MacOS/
          hdiutil create -fs HFS+ -volname ${{ env.game_name }} -srcfolder ${{ env.game_name }}.app ${{ env.game_name }}-macOS-intel.dmg

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.game_name }}-macOS-intel.dmg
          archive: false

  # Build for MacOS Apple Silicon
  build-macOS-apple-silicon:
    needs: check
    runs-on: macOS-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-apple-darwin
      - name: Environment 
        # macOS 11 was the first version to support ARM
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11"

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Download assets from google drive
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}    
          GDRIVE_ASSETS_DIRECTORY_ID: ${{ secrets.GDRIVE_ASSETS_DIRECTORY_ID }}
        run: |
          brew install rclone

          echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > /tmp/sa.json

          export RCLONE_CONFIG_GDRIVE_TYPE=drive
          export RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE=/tmp/sa.json
          export RCLONE_CONFIG_GDRIVE_ROOT_FOLDER_ID=$GDRIVE_ASSETS_DIRECTORY_ID

          rclone copy gdrive:assets assets/

      - name: Build
        run: |
          cargo build --release --target aarch64-apple-darwin -p client --no-default-features

      - name: Prepare Package
        run: |
          mkdir -p ${{ env.game_name }}.app/Contents/MacOS
          cp target/aarch64-apple-darwin/release/${{ env.binary }} ${{ env.game_name }}.app/Contents/MacOS/
          hdiutil create -fs HFS+ -volname "${{ env.game_name }}-macOS-apple-silicon" -srcfolder ${{ env.game_name }}.app ${{ env.game_name }}-macOS-apple-silicon.dmg

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.game_name }}-macOS-apple-silicon.dmg
          archive: false
